name: dl_ta
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.4.*
  - torchvision=0.19.*
  - pytorch-cuda=12.1
  - numpy
  - matplotlib
  - pillow
  - scipy
  - pandas
  - scikit-learn
  - tqdm
  - ipykernel
  - ipywidgets
  - jupyter
